### ISSUE TITLE
Default preset generates "lava caves" in the nether.

### ISSUE THREAD

**Issue by Quartofel** [PersonTheCat/CatLib#1]
Like the title says: default preset that comes with the mod generates weird "lava caves" in nether's lava lakes. I believe this is not intended:
![2022-01-02_17 45 47](https://user-images.githubusercontent.com/24753841/147882961-3c3cd6a7-d29c-438e-81c4-198495671873.png)
![2022-01-02_17 48 35](https://user-images.githubusercontent.com/24753841/147882979-e79cb1c7-7853-43d5-aa88-e540412eb2d9.png)

**Comment by PersonTheCat** [comment]
Hey, this is the wrong repository. Open your issue again for Cave Generator. I'll also need to know which version of the mod and MC version you're using. Be aware that, if this is for 1.12, I most likely will not fix the issue as I have too much else to work on for 1.16 and 1.18.
